#!/usr/bin/env node

/**
 * sync.mjs — Polyp Framework Rule Sync Engine
 *
 * Reads AGENTS.md (canonical source) and PROJECT_DNA.yaml,
 * then generates/updates all platform-specific rule files.
 *
 * Usage: node .agentile/sync.mjs
 *
 * This is a minimal V0 implementation. For production use,
 * consider adopting Ruler (intellectronica/ruler) which supports
 * 30+ agent platforms with full monorepo and CI/CD integration.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

function readFile(path) {
  try { return readFileSync(join(ROOT, path), 'utf-8'); }
  catch { return null; }
}

function writeRule(path, content) {
  const full = join(ROOT, path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content, 'utf-8');
  console.log(`  ✅ ${path}`);
}

function generateCoreRules() {
  const agents = readFile('AGENTS.md');
  if (!agents) {
    console.error('❌ AGENTS.md not found at project root');
    process.exit(1);
  }

  // Extract the Core Rules section for platform-specific files
  const rulesMatch = agents.match(/## Core Rules[\s\S]*?(?=## Platform Detection|## Terminology|$)/);
  const coreRules = rulesMatch ? rulesMatch[0].trim() : 'See AGENTS.md for rules.';

  // Extract Commands section
  const cmdsMatch = agents.match(/## Commands[\s\S]*?(?=## Core Rules|$)/);
  const commands = cmdsMatch ? cmdsMatch[0].trim() : '';

  return { coreRules, commands, fullAgents: agents };
}

function syncAll() {
  console.log('🔄 Polyp Framework — Syncing rules to all platforms\n');

  const { coreRules, commands, fullAgents } = generateCoreRules();

  const preamble = `# Auto-generated by Polyp Framework sync engine
# Source of truth: AGENTS.md
# Do not edit directly — run: node .agentile/sync.mjs
# Last synced: ${new Date().toISOString()}

`;

  const condensed = `${preamble}${coreRules}

${commands}

---
For full documentation, see AGENTS.md in the project root.
For task-specific guidance, see .agentile/skills/
`;

  // Windsurf has a 12K char limit — truncate if needed
  const windsurfContent = condensed.length > 11500
    ? condensed.substring(0, 11500) + '\n\n<!-- Truncated for 12K char limit. See AGENTS.md -->'
    : condensed;

  // ─── Claude Code ───
  writeRule('.claude/rules/00-polyp-core.md', `---
paths:
  - "**/*"
---
${condensed}`);

  // ─── Cursor ───
  writeRule('.cursor/rules/polyp-core/RULE.md', `---
description: "Polyp Framework core rules — applies to all files"
globs: "**/*"
alwaysApply: true
---
${condensed}`);

  // ─── Windsurf ───
  writeRule('.windsurf/rules/00-polyp-core.md', windsurfContent);

  // ─── GitHub Copilot ───
  writeRule('.github/copilot-instructions.md', condensed);

  // ─── Cline ───
  writeRule('.clinerules/00-polyp-core.md', condensed);

  // ─── Amazon Q ───
  writeRule('.amazonq/rules/polyp-core.md', condensed);

  // ─── Continue.dev ───
  writeRule('.continue/rules/polyp-core.md', `---
globs: "**/*"
---
${condensed}`);

  // ─── Aider ───
  writeRule('.aider.conf.yml', `# Polyp Framework — Aider configuration
# Points aider to read AGENTS.md as its conventions file
read:
  - AGENTS.md
  - .agentile/skills/tdd-strobilation.md
  - .agentile/skills/commit-conventions.md
`);

  // ─── Replit ───
  writeRule('replit.md', `# Polyp Framework Project

See AGENTS.md for full rules and conventions.

## Key Rules
- Test-first development (Strobilation Pattern)
- Conventional commits with lifecycle phases
- Architecture Decision Records for design choices
- Read .agentile/skills/ for task-specific guidance

${commands}
`);

  // ─── Codex / Devin ─── (they read AGENTS.md natively, but create override)
  writeRule('AGENTS.override.md', `# Polyp Framework Override
# This file takes precedence over AGENTS.md for platforms that support it.
# Currently empty — add project-specific overrides here.
`);

  console.log('\n✅ All platform rules synced from AGENTS.md');
  console.log('   Platforms updated: Claude Code, Cursor, Windsurf, Copilot,');
  console.log('   Cline, Amazon Q, Continue.dev, Aider, Replit, Codex/Devin');
}

syncAll();
